# Generated by Django 4.0.5 on 2022-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
