# Generated by Django 4.0.5 on 2022-06-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена тура', 'verbose_name_plural': 'Цена туров'},
        ),
    ]
