# Generated by Django 4.0.5 on 2022-06-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='tour_image/')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_image', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Картинка тура',
                'verbose_name_plural': 'Картинки туров',
            },
        ),
    ]
