# Generated by Django 4.0.5 on 2022-06-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_benefits_options_alter_price_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
