# Generated by Django 4.0.5 on 2022-06-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_image',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_additional_images', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='tour_image',
            name='image',
            field=models.ImageField(upload_to='tour_additional_images/'),
        ),
    ]
