# Generated by Django 4.0.5 on 2022-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_image_tour_alter_tour_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_image',
            old_name='image',
            new_name='tour_image',
        ),
    ]
