# Generated by Django 4.0.5 on 2022-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_image_tour_image_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_image',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour_image',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
