# Generated by Django 4.0.5 on 2022-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tour_image_tour_tour_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_plan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
