# Generated by Django 4.0.5 on 2022-06-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_plan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_plan',
            name='slug',
        ),
    ]
