# Generated by Django 4.0.5 on 2022-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_country_details_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_details',
            name='area',
            field=models.IntegerField(),
        ),
    ]
