# Generated by Django 4.0.5 on 2022-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_country_details_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
