# Generated by Django 4.0.5 on 2022-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_facebook_settings_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'О компании ',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_partner', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на партнера')),
                ('image', models.ImageField(upload_to='parners/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('position', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Команду',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
