# Generated by Django 4.0.5 on 2022-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about_partners_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
