# Generated by Django 4.0.5 on 2022-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
